### ISSUE TITLE
As a researcher, I want the structured text file and incipits parsed into canonical stories, story instances, and manuscripts and imported into Google Sheets so I can work with the data in a more structured form.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/pemm-scripts#11]
- [x] document functions/methods
- [x] put generated file in an output folder that is git ignored; maybe add datestamp to filenames?
- [x] mss ids like PEth 41.8 and EMIP 601.225 should only use the number _before_ the period. The number after the period should go in the order field - applies to PUL, EMIP, and maybe EMDL. 
- [x] If there is a question mark after the period, ignore it (#.?)
- [x] for imported incipits: mark as macomber incipit (new field) and set confidence to high 
- [x] for mss references with numbers not in parens, like ZBNE 60-29 and CRA 52-35 and SBLE 32-28 : the number after the the dash should go in the story order field, there are no folios
- [x] in the **MSS:** line, use the previous repository/collection for subsequent references if not specified (i.e. in ZBNE 60-29; 61-27; are both ZBNE.)
- [x] Put 'English translation:' contents into new canonical story field of same name
- [x] Put 'Text:' contents into new canonical story field 'Print Version'
---
additional changes 2/24/2020
- [x] make folio notation consistent: convert all "r" to "a" and all "v" to "b"
- [x] handle single-manuscript collections:  C-, CL-, CBS-, and G- only have 1 mss, so the number that follows is the miracle order. Give them all manuscript id 1.
- [x] only infer folio start = folio end for single folios if manuscript is in PEth, EMDL, or EMIP (leave folio end empty for all others)

**Comment by WendyLBelcher** [comment]
Just a note to say that the issue of "mss ids like PEth 41.8 and EMIP 601.225" is important.  Just in case it is getting lost in the mix. I don't know how to comment field!

**Comment by rlskoeser** [comment]
@WendyLBelcher it's on my list! I'm sorry I haven't been able to get back to it yet. I started looking at it but discovered I needed to add some tests before I updated my script because I'm handling so many different cases now, and was worried about breaking things I already have working...

**Comment by rlskoeser** [comment]
Increasing from 3 to 5 pts for the complexity of handling variation in manuscript references and available information.

**Comment by rlskoeser** [comment]
Problem documented by @elambrinaki on https://github.com/Princeton-CDH/pemm-scripts/issues/29
> On the Story Instance sheet, there are repeating rows, which I assume is the result of import of the manuscripts that are separated by ";" with no manuscript name repeated.

> For example, on the Story Instance sheet, Canonical Story ID 404 is matched to G-Vatican (BAV) 92 three times. In the primary source, MAC0404 is listed in three different G-Vatican (BAV) manuscripts (GVE 92(7a); 146(69b); 242(23b)). In our Google sheets, instead of having three different rows with G-Vatican (BAV) 92 folio start 7a, G-Vatican (BAV) 146 folio start 69b, and G-Vatican (BAV) folio start 242 (23b), we have three identical rows (G-Vatican (BAV) 92 7a).

> The same thing with this story and CR-Paris (BNF) 52. In the primary source, there are three manuscripts (CRA 52-91; 52(12a); 55(10b)), so the import should result in 1) CR-Paris (BNF) 52, miracle number 81, 2) CR-Paris (BNF) 52, folio start 12a, 3) CR-Paris (BNF) 55, folio start 10b.

- [x] fix logic for repeated manuscripts within one repository

**Comment by WendyLBelcher** [comment]
- [x] For conversion of text file, change 'BM': 'B-Oslo (SCOL)',
- [x] For conversion of text file, change 'WBLE': 'W-London (BM)',

**Comment by rlskoeser** [comment]
Revised to correct the repository mapping and correct logic for repeating manuscripts when manuscript name/repository does not repeat.

**Comment by WendyLBelcher** [comment]
I believe this Issue can be closed.
