### ISSUE TITLE
As a researcher, I want to easily compare story incipits in Google Sheets against known high-confidence incipits so that I can select the story represented in the data.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/pemm-scripts#16]
# dev notes
this is the UI implementation of #13, the incipit search functionality. it could be dependent on a chore or other backend work to write the web service that will send data to the UI.
### client (script embedded in sidebar)
- [ ] incipit search request (pick a particular incipit and send it to server to do search)
- [ ] incipit search success handler (update sidebar content with results)
- [ ] incipit choice handler (call server to update relevant rows of sheet)
- [ ] generic http request failure handler (log error, show error in sidebar?)
### server (apps script functions)
- [ ] request data from incipit search web service for a given incipit, parse, and return it
- [ ] take selected macomber id and update relevant rows in the sheet

**Comment by rlskoeser** [comment]
No longer makes sense to integrate the incipit tool into google sheets; having it as a standalone flask app that we can iteratively revise and refine has turned out to be a good solution.
