### ISSUE TITLE
Changes to PEMM Google Sheet and Incipit Tool

### ISSUE THREAD

**Issue by WendyLBelcher** [Princeton-CDH/pemm-scripts#25]
PEMM Google Sheet columns
Story Sheet
One aim we have is to distinguish the relative length of story instances. To do that, we need to be able to calculate accurately the number of characters in the story. To do that, we need a little more information collected by the cataloger. So, we need to add some columns.
- So, please add the following columns, after the Column "Line End"

- Columns per page   (validation should be to a digit 1-9, no letters; mostly the columns will be 2, sometimes 1, sometimes 3, almost never anything else)
- Lines per column   (validation should be digit 1-99, no letters; mostly the lines will be 10 to 30)
- Characters per line  (validation should be digit 1-99, no letters; mostly the characters will be 10 to 20)       
- Empty Lines  (validation should be digit 1-999, no letters; this column will be 0 99% of the time; if it has a number, it can be anything)              
- Story Incomplete   (no validation, this is a note field)  
- Ethiopic story number   (validation should be a digit 1-999, no letters; mostly the numbers will be 1 to 300)

**Comment by thatbudakguy** [comment]
Let's keep this issue for discussing the proposed schema changes, and I'll move the synonym/incipit-tool related material to a new issue (#27).

**Comment by thatbudakguy** [comment]
For "columns per page", "lines per column", and "characters per line" - are these properties of a particular story instance, or of a manuscript? That is, are manuscripts consistent about the number of columns, characters per column, etc. throughout? Conversely, are there instances where they change _per page_ (maybe just some anomalous pages within stories)?

**Comment by thatbudakguy** [comment]
For "Ethiopic story number" - where does this come from? Is it a property of a story instance, or of a canonical story?

**Comment by thatbudakguy** [comment]
For "story incomplete" - could we just store this information in the existing notes field, perhaps with a tag like "INCOMPLETE"?

**Comment by WendyLBelcher** [comment]
Re "columns per page", "lines per column", and "characters per line" @rebeccakoeser and I discussed this and they are properties of a particular story instance. That is, manuscripts vary so much that we might as well do it per story. One manuscript will have a first section that is one column, and a second with two, and written by two different scries, one with cramped handwriting, one with wide. It most cases it won't vary, but in some it will.

**Comment by WendyLBelcher** [comment]
Re Ethiopic Story Number, this is for the Story Instance sheet. This was Vita's suggestion. Some of the manuscripts actually give a number in the manuscript, in fidel, for each story. Like, a big 55 in the margin before the 55th miracle story in the manuscript. This number will most likely match what is in the Story Number field, but sometimes it won't and it will help catalogers to find the story quickly if we have this data. This field will be empty for about 75% of manuscripts.

**Comment by WendyLBelcher** [comment]
Re Story Incomplete (with validation set to Yes, No), it is important to have that column. It's kind of like that High confidence, medium confidence, low confidence column on the incipit, but for character count. That is, let's say we have 100 manuscripts with the cannibal story. 75 of them are around 2,000 characters long; 24 of them are around 1500 characters long; and one is 500 characters long. This might be an exciting new discovery. Or it might mean that a folio missing. So, if it is marked "story incomplete" we know that the story is not some weird new short version, but rather that a folio went missing.

**Comment by WendyLBelcher** [comment]
Out of scope, so closed.
