### ISSUE TITLE
Problem with importing manuscripts separated by ";" without repeating the manuscript name

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#29]
On the Story Instance sheet, there are repeating rows, which I assume is the result of import of the manuscripts that are separated by ";" with no manuscript name repeated.

For example, on the Story Instance sheet, Canonical Story ID 404 is matched to G-Vatican (BAV) 92 three times. In the primary source, MAC0404 is listed in three different G-Vatican (BAV) manuscripts (GVE 92(7a); 146(69b); 242(23b)). In our Google sheets, instead of having three different rows with G-Vatican (BAV) 92 folio start 7a, G-Vatican (BAV) 146 folio start 69b, and G-Vatican (BAV) folio start 242 (23b), we have three identical rows (G-Vatican (BAV) 92 7a).

The same thing with this story and CR-Paris (BNF) 52. In the primary source, there are three manuscripts (CRA 52-91; 52(12a); 55(10b)), so the import should result in 1) CR-Paris (BNF) 52, miracle number 81, 2) CR-Paris (BNF) 52, folio start 12a, 3) CR-Paris (BNF) 55, folio start 10b.

**Comment by rlskoeser** [comment]
@elambrinaki thanks for identifying this problem and providing examples. I'm moving it to #11 since it's a problem I need to correct before we can complete that one.
