### ISSUE TITLE
As a researcher, I want data from Google Sheets synchronized to a GitHub repository to include contributor information so that people working on the data get credit for their work.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/pemm-scripts#31]
## testing notes
There is a new **_contributor** sheet in the test spreadsheet that is used to map google email addresses to GitHub emails and usernames.
- [x] if you make a change and your information is in the contributor sheet, you should be listed as a co-author when the change is added to github
- [x] if you make a change and your information is _not_ in the contributor sheet, the changes should be synchronized without a co-author message
- [x] if multiple people make changes and have github information in the sheet, they should all be listed as co-authors

## dev notes
- [x] on script startup, check for and load JSON file with last modification information based on document id
- [x] use last modification to determine if the script needs to run (bail out if no changes)
- [x] if there are changes, use the revision history to determine contributors
- [x] get github contributor details from contributor sheet
- [x] generate coauthor text for git commit message
- [x] exclude contributor sheet from data synchronized to github
- [x] save/update json file with last modification info

**Comment by WendyLBelcher** [comment]
I tested the first item above. i couldn't test the second. I will ask Evgeniia to help me with the third.

**Comment by elambrinaki** [comment]
The second condition is tested. It works -- no co-author message.

![Image 3-17-20 at 3 06 PM](https://user-images.githubusercontent.com/34317046/76892554-43648900-6861-11ea-899d-100faa541960.jpeg)

**Comment by elambrinaki** [comment]
Since I am not a contributor, I cannot test the last item. Wendy and Rebecca should edit the file simultaneously, am I right?

**Comment by elambrinaki** [comment]
As I am a contributor now, I tested the fist item -- it works.

**Comment by elambrinaki** [comment]
Re co-authorship, only the last contributor is mentioned on Github.

Here some changes were Wendy's, some were mine. Wendy didn't receive any credit.

![Image 3-17-20 at 6 20 PM](https://user-images.githubusercontent.com/34317046/76907269-2d17f680-687c-11ea-9357-c023f86c4701.jpeg)

**Comment by rlskoeser** [comment]
Tested again with multiple revisions by multiple users (over a longer time period) and the commit message included multiple users.
![Screen Shot 2020-03-19 at 2 40 41 PM](https://user-images.githubusercontent.com/691231/77102769-bac82300-69ef-11ea-8326-f3dbee96974c.png)
