### ISSUE TITLE
Manuscript Sheet validation correction

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#34]
1. Can you please remove validation from Century column? It is not working now, and we would like to have it in the text format.
2. Could you please correct validation for Date Range Start and Date Range columns? (both should allow any four digit number that starts with 1)
![Буфер обмена-1](https://user-images.githubusercontent.com/34317046/77867050-9d6f3200-7203-11ea-80de-1d700824f2ef.jpg)

**Comment by rlskoeser** [comment]
Please test validation on this [test spreadsheet](https://docs.google.com/spreadsheets/d/1QgrpkYlsshG6sIlPXwtN-ZojOT4EPyHpnjyrK_D12gI/edit#gid=1231560155) (made as copy of the master data sheet with new data validation applied for testing.) 

- [ ] century validation and formatting have been removed
- [x] date range start and end validation are now bound to the correct fields

**Comment by elambrinaki** [comment]
Date Range Start/End columns are working great.

Century column validation is still in place.

**Comment by rlskoeser** [comment]
@elambrinaki I didn't think about the fact that it wouldn't remove existing validation. To test that the updated code now doesn't add the century validation, please remove validation manually and change the formatting, then choose "Set up validation" from the PEMM menu. It shouldn't add any validation to the century column or change the formatting.

**Comment by elambrinaki** [comment]
The century column is free of validation, and it is formatted as text.
Thank you!
