### ISSUE TITLE
Protect spreadsheet header rows

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/pemm-scripts#36]
Per suggestion from @elambrinaki  - since we don't really want the headers to be change (and some things will break if the do), it would be helpful to have the header row on each sheet marked  as protected to avoid problems.

**Comment by kmcelwee** [comment]
@rlskoeser didn't we do this to some degree? Or is this outdated?

**Comment by rlskoeser** [comment]
We never integrated into the google apps script code (Evgeniia may have done it manually in the actual spreadsheet, I don't know).

**Comment by elambrinaki** [comment]
@kmcelwee @rlskoeser Yes, the header row is a protected range in the PEMM Google sheet.
