### ISSUE TITLE
As a researcher, I want a way to exclude high-confidence incipits from the Incipit Tool so that incipits entered with typos or mistakes are not included in the search.

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#39]
We need a new checkbox column "Exclude from ITool" on the Story Instance sheet. A story might be High Confidence, but its incipit shouldn't go into the Incipit Search Tool (for example, it is shorten, or typed in with mistakes).

**Comment by rlskoeser** [comment]
@elambrinaki where in the column order should this be added? It makes sense to me to put it after the confidence score.

We've kept the setup code deliberately simple, so it doesn't modify the rows or columns, it just adds the headers and named ranges and applies validation. I think the simplest approach for now would be to manually add the column where we want it and then run the setup script — does that seem reasonable to you?

Field name: I see your suggestion "Exclude from ITool"; are you calling it that elsewhere? Would "Exclude from Search" make sense / be specific enough?

**Comment by rlskoeser** [comment]
Have copied current master spreadsheet and applied new code to test. 
Please test on [this test spreadsheet](https://docs.google.com/spreadsheets/d/19Y0XYKBySobV1dmYnVKqjzp1Z_F21321a5saSAQlUVE/edit#gid=1231560155).
Run through these steps to apply the new code:
- Manually add a new column on the story instance sheet before the Notes
- Use PEMM menu -> setup all sheets
- Use PEMM menu -> setup validation

Check that: 
- [x] New column has been added before the notes field with the correct title
- [x] New column is formatted as a boolean / checkbox field
-  [x] Check the box for a high confidence incipit and wait for test site to update the index (:03 every hour), then confirm that the incipit is no longer in the search results

**Comment by elambrinaki** [comment]
Everything works!

New column has been added with the right format:
![Exclude from ITool](https://user-images.githubusercontent.com/34317046/82319112-04f16480-999f-11ea-980b-6577967ab188.jpg)

Testing ID 136 from newly cataloged mss EMML 9002:
![ID 136 from EMML 9002](https://user-images.githubusercontent.com/34317046/82319176-1dfa1580-999f-11ea-978e-6e43c79aaea6.jpg)

Testing excluding original Macomber incipit:
![Excluding Macomber incipit](https://user-images.githubusercontent.com/34317046/82319258-3c601100-999f-11ea-8eee-1bff3fe684d9.jpg)

![ID 116  from EMML 3872 (Macomber incipit)](https://user-images.githubusercontent.com/34317046/82319270-4124c500-999f-11ea-9bfb-3343b396c001.jpg)

In both cases, the excluded incipit does not appear in the search results.

**Comment by rlskoeser** [comment]
@elambrinaki great, so can this be closed?

**Comment by elambrinaki** [comment]
Yes!
