### ISSUE TITLE
Manuscript sheet, Date Range field validation 

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#42]
Hi Rebecca @rlskoeser!
I'm having trouble with Date Range Start/End fields on the Manuscript sheet. I cannot enter 4-digit years in the new rows (and for some old records, there is a flag "This cell's content violates its validation rule"). 
We had this problem before, and you fixed the code (there was a wrong column in the validation rule) and we run the PEMM script to set up the new validation. Could I have this problem again because of new rows? Could it be that the new validation rules applied to only the rows existed at that moment, but the new rows have the old validation? Re the flags for the old recods, I did insert rows between the old records, so their position has changed.

**Comment by rlskoeser** [comment]
@elambrinaki would you try re-applying validation from the PEMM menu to see if that solves this problem?

**Comment by elambrinaki** [comment]
@rlskoeser I did. It doesn't seem to solve the problem.

**Comment by elambrinaki** [comment]
It works!
