### ISSUE TITLE
Changing Named ranges

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#43]
When I reapplied validation from the PEMM menu, the data on other sheets shifted. I think it is because named ranges are definied without $ sign, and since I added rows at the beginning, the named ranges shifted (for some fields, they now begin from row 3 or 4 instead of row 2).

**Comment by rlskoeser** [comment]
I have a potential fix for that #35 — but I thought we agreed to add unmanaged columns at the end of managed columns?

**Comment by elambrinaki** [comment]
@rlskoeser Right, all new columns are at the end, But for rows, we didn't make the same agreement. So I add rows not only at the end, but anywhere I need them.

**Comment by rlskoeser** [comment]
Sorry, I didn't read carefully enough! It didn't seem like adding rows wouldn't be a problem, but if you added them before the first entry then it could indeed mess up the reference.

**Comment by rlskoeser** [comment]
@elambrinaki sorry, I don't understand what you're asking us to do. If you run the "setup sheet" command it will redefine the ranges — does this help any?

**Comment by elambrinaki** [comment]
@rlskoeser Indeed, in the [test PEMM sheet](https://docs.google.com/spreadsheets/d/19Y0XYKBySobV1dmYnVKqjzp1Z_F21321a5saSAQlUVE/edit#gid=1282213332) after running the setup sheet the named ranges look good:

![Named ranges](https://user-images.githubusercontent.com/34317046/82321366-bba31400-99a2-11ea-8726-441cd981def2.jpg)
