### ISSUE TITLE
Include help text in the schema file and automatically add as notes to headers

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#44]
Currently we have notes explaining the purspose of columns on a second row, below column headers. We want to add these notes to the schema file in the code so that they could be applied directly to the header row when we run the setup sheet step. For this, Rebecca will put the code into a brunch.

We want to test whether we can edit notes that are automatically created. We can use notes on the Story Instance sheet for this.

If it turns out we cannot edit automatically created notes, we will put the notes in the schema later once they’re more settled.

**Comment by rlskoeser** [comment]
- [x] Review [schema.json file](https://github.com/Princeton-CDH/pemm-scripts/blob/develop/src/schema.json#L5-L38) to see how notes have been added for the story instance fields.
- [x] Check for notes on story instance sheet after running setup step.
- [x] Check that headers on other sheets do not have comments

**Comment by elambrinaki** [comment]
@rlskoeser I also removed the note for the Manuscript column to see whether it would cause problems for the Incipit Search Tool (and edited the note for the Folio Start column).

Editing seems to be harmless, the ITool keeps working.

**Comment by rlskoeser** [comment]
@elambrinaki how do you want to proceed with this one? Do you want me to add the other notes?
