### ISSUE TITLE
Rename Macomber Incipit to Canonical Incipit

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#47]
@rlskoeser May I please ask you to rename the **Macomber Incipit** column on the Story Instance sheet to the **Canonical Incipit**? Wendy has just found 45 new miracles (not used by Macomber), and we added another four earlier. So, the total number of non-Macomber canonical stories is already around 50 (out of 640 stories), i.e. a solid share. These stories need a canonical incipit, and we cannot call it Macomber incipit.

**Comment by rlskoeser** [comment]
@elambrinaki this is the checkbox field, right? I don't remember what we were using that field for, I thought it was to track which incipits were from Macomber. Are you now using it for something else, so that you can designate the best or most representative incipit for a given story?

**Comment by elambrinaki** [comment]
@rlskoeser Exactly! Canonical Incipit field would mean this is the most representative incipit (or one of several most representative incipits) for a story. Initially, Macomber incipits were the same as canonical incipits, but with new stories, Macomber incipits are a subset of canonical incipits.

Yes, this is the checkbox field. In terms of the code, I think during import records with Macomber Incipit field checked were automatically assigned the High Confidence score, so they were added to the Incipit Search Tool. I don't know any field that is based on values in Macomber Incipit column.

**Comment by rlskoeser** [comment]
@elambrinaki could you suggest revised help text for the renamed field? Currently I have this in the code:
> The column is locked (it shows which incipits are from Macomber)

**Comment by elambrinaki** [comment]
@rlskoeser "The most representative incipit for a story (or one of several most representative incipits if a story has very distinct recensions)."

We'll be able to edit the notes anyway.

**Comment by rlskoeser** [comment]
@elambrinaki sure, but it help us to have it documented in the code.

I've updated the qa test document we were using with this change. Would you re-run the setup and validation steps to confirm? It should:
- [x] use the new label
- [x] use the new help text
- [x] still apply formatting/validation to make it appear as a checkbox

**Comment by elambrinaki** [comment]
@rlskoeser Everything looks right.
