### ISSUE TITLE
Show 50 results instead of 10 for incipit search

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/pemm-scripts#50]

**Comment by kmcelwee** [comment]
I hardcoded the parameter request as 
```python
results = queryset.get_results(rows=50)
```
because I couldn't find it exactly in `parasolr`. I did find in [L78 of `queryset.py`](https://github.com/Princeton-CDH/parasolr/blob/master/parasolr/query/queryset.py#L78) the following note:
```
TODO: what do we do about the fact that Solr defaults to 10 rows?
```
So I assume that it's something that's come up before? Let me know if it's worth coding up a specific rows function in `parasolr`

**Comment by elambrinaki** [comment]
Showing 50 results seems extreme to me :) A lot of them will be completely irrelevant. In addition, no one will ever scroll down to the bottom of the page, and thus no one will see our beautiful logo
![logo](https://user-images.githubusercontent.com/34317046/83546959-841e8680-a4cf-11ea-847a-451dc7ad0b40.jpg)

Can we discuss the appropriate number on Thursday?

**Comment by rlskoeser** [comment]
@elambrinaki agreed that 50 is a lot. I wonder if 20 is a better number, but it does sounds like we should discuss our options and decide which approach to take — whether grouping results in some way, increasing the number of results.

**Comment by rlskoeser** [comment]
@kmcelwee that's a reasonable solution. I think you should also be able to use array brackets / slicing notation on the result, but this seems clear to me.
