### ISSUE TITLE
As a data editor, I want a way to create sheets that are ignored by the script that automatically synchronizes data to a git repository.

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/pemm-scripts#52]
(Placed here instead of `pemm-data` to keep on ZenHub) Currently, we ignore the "_contributors" sheet when creating CSVs, but we also want to ignore "instructions". Instead of adding "instructions" to the list of ignored sheets, we should instead write a rule for github to ignore all sheets that start with an underscore, allowing @WendyLBelcher and @elambrinaki to experiment more freely.

**Comment by kmcelwee** [comment]
@WendyLBelcher @elambrinaki This worked as expected! Sheets starting with an underscore are ignored, as shown in the pemm-qa-data repo. RSK or I will need to delete instructions.csv and _instructions.csv from pemm-data the next time we deploy to production.

**Comment by kmcelwee** [comment]
Hi @elambrinaki, please make sure this is working correctly!
- [x] Add two sheets to QA PEMM, one starting with and one not starting with an underscore.
- [x] Go to pemm-qa-data and confirm that the CSVs were appropriately synced
- [x] Document results

**Comment by elambrinaki** [comment]
@kmcelwee In addition to instructions.csv and _instructions.csv, could you please also delete macomber_incipits.csv, _macomber_incipits.csv, and sheet2.csv from the pemm-data repo (Macomber Incipits sheet was added for cataloging and will be deleted later; sheet2 is no longer in PEMM)?

**Comment by elambrinaki** [comment]
@kmcelwee It works as expected.
I added Testing Underscores and _Testing Underscores sheets. 
testing_underscores.csv appears in the pemm-qa-data GitHub repository, _testing_underscores.csv does not.
