### ISSUE TITLE
Set up preliminary data validation 

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/pemm-scripts#55]
Integrate basic error checks to catch mistakes that might come up with data entry

- [x] start with a CI task that runs [goodtables](http://frictionlessdata.io/tooling/goodtables/#check-it-out); prefer using GitHub Actions if we can

**Comment by elambrinaki** [comment]
@kmcelwee How does the test on whether a story is given a wrong ID work? Does it catch only cases when two stories with _exactly the same_ incipit are given different IDs, or can it also identify cases when two stories with _quite similar_ incipit are given different IDs? We are checking the former (column "Test for whether the incipit is not unique" on the Story Instance Sheet). Having a more complicated test for _similar_ (but not identical) incipits with different IDs will be very useful.

**Comment by kmcelwee** [comment]
I've created a test script to migrate raw data to a new directory. You can read through it here https://github.com/kmcelwee/pemm-jupyter/blob/master/Follow%20schema%20when%20migrating.ipynb. This script uses the original schema to filter columns and removes empty rows.

Notes:
* Please forgive the pandas usage, I can go back and change if necessary
* It's easier to work off an existing file for these kinds of manipulations. Is it inappropriate to just write the raw file to the VM?
* On your green light, I could move this into `gsheets_to_git.py`, but I feel like a separate cleaning / validation script might be more clean. Thoughts?

**Comment by rlskoeser** [comment]
For the first pass validation on continuous integration — probably makes more sense to use http://goodtables.io/

**Comment by kmcelwee** [comment]
@rlskoeser I'm only just seeing "start with a CI task that runs goodtables; prefer using GitHub Actions if we can", I've very sorry about that

**Comment by kmcelwee** [comment]
I’ve created a github actions workflow that runs goodtables on each CSV (without those row limits). https://github.com/Princeton-CDH/pemm-data/pull/3

The CLI in actions allows us to also error check along a schema; however, if we want to go that indepth with validation, we’ll need to go column by column with @WendyLBelcher  and @elambrinaki to answer the following questions.

* What kind of data is in this column?
	* Numerical: what ranges?
	* Categorical: what are the categories?
	* String: what language? should other languages be excluded?
* Are all the values in this column supposed to be unique?
* Should there be any empty cells in this column?

But that is probably out of scope. For this first round of data cleaning (to pass preliminary goodtables validation) we need to remove empty and duplicate columns and rows.

Furthermore, we need to figure out how we’ll divide responsibilities for cleaning the data. While some measures can be taken to keep the CSVs on GitHub clean, those cleanings would not be reflected in the Google Sheets.

**Comment by kmcelwee** [comment]
This seems like it repeats #54, so I assume this is closed as well?

**Comment by rlskoeser** [comment]
@kmcelwee I was thinking of keeping it open since we had ideas about other validation and reporting — but we could also close this task and make a new task (or tasks) for follow up. I'm fine with either, what do you think?

**Comment by kmcelwee** [comment]
I feel like this issue is too vague to be useful, especially given what we know now. (And your original checklist on this is completed.) I think there are issues that will need to be created around data validation & report generation, but I think starting with fresh issues may be more useful. Or just rename this into an epic? You have a better idea of what the dev team thinks the life of an issue should be.

**Comment by rlskoeser** [comment]
@kmcelwee I expected we would add more items to the check list! But I agree, as it stands now this issue isn't useful. I think it makes sense to drop the "report generation" from the issue and close it.

**Comment by rlskoeser** [comment]
Revising to reflect basic validation that's been implemented and closing, per conversation with @kmcelwee. We should make new issues with specific details about validation or reporting we plan to implement.
