### ISSUE TITLE
As a cataloger, I want to see which matches for my search are canonical incipits so I can use that to help decide which identifier to choose.

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#58]
We need to add labels ("Canonical Incipit") to the search results that come from rows with the "Canonical Incipit" field checked. 
## dev notes
- [x] update indexing script to index canonical incipit boolean field in Solr
- [x] update flask view to include canonical incipit field in Solr returned values
- [x] update flask template to display canonical incipit indicator based on the boolean

**Comment by elambrinaki** [comment]
For example, I have an incipit matching with the incipit from GEM (PUL) 17 50r (the first search result). 

![ID 158 or 155](https://user-images.githubusercontent.com/34317046/83969887-80f51300-a8a0-11ea-9518-a2baf0e47a20.jpg)

However, this incipit was added by another cataloger; it is not the canonical incipit for ID 158. Because there are three ID 155 among the top five search results, I might be cautious assigning my story ID 158. The canonical incipit for ID 155 is the third search result.

"canonical incipit" labels will help me realize that
1. the first search result is not the canonical incipit for ID 158
2. among the three search results for ID 155, the second is the canonical incipit

This information will guide my choice of ID for the story.

**Comment by elambrinaki** [comment]
The label could look something like
![Canonical Incipit label_3](https://user-images.githubusercontent.com/34317046/83973774-83626780-a8b6-11ea-9820-dc0935d8c0d5.jpg)

Copying Wendy's words: "It's important information, but we don't want to signal that it is the best somehow. So, in gray, to the right."

**Comment by rlskoeser** [comment]
thanks @elambrinaki — I've revised the issue to rewrite as a user story, please check that it makes sense to you and captures the "why" of this feature (feel free to revise).

**Comment by elambrinaki** [comment]
@rlskoeser Looks great! Thank you @rlskoeser

**Comment by rlskoeser** [comment]
@elambrinaki this is available on the test site now — please confirm that it works as expected. To test thoroughly, probably a good idea to change some of the canonical incipit values in the QA TEST PEMM spreadsheet and confirm that the index is updated and they appear correctly.

**Comment by elambrinaki** [comment]
The Canonical Incipit labels appear in the search.
![Canonical Incipit](https://user-images.githubusercontent.com/34317046/85292003-44611400-b469-11ea-917d-30ceae4ef702.jpg)

After editing the canonical incipit in the QA TEST PEMM spreadsheet, the updated incipit appears in the search with the canonical incipit label attached.
![Canonical Incipit_edited](https://user-images.githubusercontent.com/34317046/85292163-7ecab100-b469-11ea-80da-e0d802ae91c5.jpg)
