### ISSUE TITLE
As a researcher, I want the Macomber keywords from the structured text file added to Canonical Story data in Google Sheets to use as a reference when creating a standardized list of keywords

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#59]
Could you please help us with importing the Macomber keywords from the [Sublime Text file](https://github.com/Princeton-CDH/pemm-scripts/blob/master/data/macomber-miracles.txt) to the PEMM Google sheet? They can all go into a single field ("Macomber Keywords") on the Canonical Story sheet.
As an example, I added the keywords for ID 1-A:
![Macomber keywords column](https://user-images.githubusercontent.com/34317046/83969614-fd86f200-a89e-11ea-9233-19fd555ba595.jpg)

**Comment by rlskoeser** [comment]
@elambrinaki have revised the issue to user story format, please revise and add the why/motivation

**Comment by kmcelwee** [comment]
I just pasted the keywords into the column. I used a jupyter notebook to map the column's ids to the json I've just created in the attached PR. I then pasted the column into Sheets.

Hi @elambrinaki, would you mind:
- [x] Checking that the keywords line up in the spreadsheet? I triple checked, but it would be great to have fresh eyes on it. There are some Macomber IDs that do not have keywords.
- [x] Giving us the green light to close this issue if appropriate

**Comment by rlskoeser** [comment]
@elambrinaki do you want to keep the Macomber Keywords after the notes column or would you prefer to have it before?

**Comment by elambrinaki** [comment]
Thank you very much @kmcelwee! Everything looks great, you can close the issue.
@rlskoeser I think we can leave them after the Notes column. It is possible we will move the keywords the students generate to this sheet as well, so it would be nice to have Macomber keywords and the new list of keywords next to each other.
