### ISSUE TITLE
As a researcher, I want to have a map with Ethiopian locations to analyze how the stories disseminated over time and space

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#61]
**Motivation**
We need a map with Ethiopian locations that has two layers, one for manuscripts and one for stories.
The manuscripts map shows where the manuscripts came from. The stories map allows to select a miracle and a century and to view all locations in which that miracle was told in the chosen time period. 
The manuscripts map shows the representativeness of the data we have. There might be no records of a miracle in a certain region because that miracle wasn’t known there, or because we don’t have manuscripts from that region in the database. So the manuscripts map is needed to interpret the data on the stories map.

The maps will help us analyze how the stories disseminated over time and space.

**Data sources**
The data (latitude and longitude) for the manuscripts map comes from the Manuscript sheet, columns Latitude and Longitude.
The data (latitude, longitude, century) for the stories map comes from the Story Instance sheet,  columns Story Century, Story Latitude, Story Longitude.

**Map interface** 
An example of how the map might look like:

![Map with filters](https://user-images.githubusercontent.com/34317046/84215768-5a4bfd80-aa95-11ea-87d2-fdd35e1b117c.jpg)

- There are two dropdown lists, one for ID, another for century. 
- IDs options are all IDs from the Canonical Story sheet. 
- The century options are 15th, 16th, 17th, 18th, 19th, 20th, Any century.
-- “Any century” view allows to find regions in which the story was never told.
- On the background, the manuscripts locations are shown as a reference.

**Comment by rlskoeser** [comment]
Have determined that the data is not ready for mapping at this point. Recommend that the team use Palladio + OpenRefine for exploring the data when it is ready.
