### ISSUE TITLE
As a cataloger, I want to see recension identifiers in the Incipit Search Tool so that I could find out not only a story ID, but also a recension

### ISSUE THREAD

**Issue by elambrinaki** [Princeton-CDH/pemm-scripts#65]
About 50 Macomber IDs have two or three story variations. For each story variation, we have an incipit from Macomber. Newly cataloged stories always match one of the Macomber variations better than the other, and we want to record which one.

For this, we need to have both stories IDs and recensions IDs in the search. For example, ID 135 has two distinct versions. One version appears in manuscript EMML 2059. Another version is told in EMML 3872. We want to use extended IDs "135 [EMML 2059]" and "135 [EMML 3872]" for them, and we want the incipits for these two stories to be listed as "135 [EMML 2059]" and "135 [EMML 3872]" (instead of "136" for both) in the Incipit Search Tool. 

I added a column "Story ID with Recension ID" in the [QATEST PEMM](https://docs.google.com/spreadsheets/d/19Y0XYKBySobV1dmYnVKqjzp1Z_F21321a5saSAQlUVE/edit#gid=1274751673) and copied Story ID values for all stories that have incipits (i.e. the Incipit column is not blank, so these records could be in the Incipit Search Tool). For the stories that have multiple recensions, I will add an ID extension in this column. After that, I want this column to be used in the ITool instead of the Canonical Story ID. 

To begin, I took ID 135 that has two recensions. In the database, there are five records with this ID: from EMML 2059, EMML 3872, EMML 9002, PEM 41, PEM 8. Using the Incipit search tool, I could identify two clusters: EMML 2059, EMML 9002, PEM 8 are all "135 [EMML 2059]", and EMML 3872, PEM 41 are "135 [EMML 3872]". I inserted this into the "Story ID with Recension ID" column. Now if a user of the Incipit Search Tool has a story with ID 135, she will also receive information about the story's recension (assuming the Incipit Tool uses this new column for records IDs).

I will repeat the process for other IDs that have multiple recensions to update the Incipit Tool. After that, the catalogers will be able to create records with information about recensions. To signal that they need to record a recension ID along with the story ID, we can apply the following conditional format rule: if the ID they have selected in the Canonical Story ID column is one of those 50 IDs that have extensions and they inserted an incipit, color the row in green (as an example, I did it in the [QATEST PEMM](https://docs.google.com/spreadsheets/d/19Y0XYKBySobV1dmYnVKqjzp1Z_F21321a5saSAQlUVE/edit#gid=1274751673) sheet for ID 135). Green rows will mean the story's recension can be identified.

----

## dev notes
~- [x] add "Recension ID" field to story instance directly after "Story ID"~
~- [x] add help text "Manuscript ID for the canonical version of this story variation"~
~- [x] configure validation: Recension ID should be in the list of manuscript ids~
- [x] index recension id in Solr
- [x] when a match has a recension id, display story id & recension id in tabular form for easy cut and paste into the spreadsheet
- [x] update pemm-data schema for rename from "ID Extension" to "Recension ID"

**Comment by rlskoeser** [comment]
@elambrinaki thanks for all your work on this and for the details you've documented here.

I don't understand why you're adding a "story id with recension id" — don't we just need an optional recension id or label field that you would fill out for stories that have recensions? 

@WendyLBelcher how do you normally refer to or differentiate recensions of the same story? Would it be best to use numbers, letters, a short label?

**Comment by elambrinaki** [comment]
@rlskoeser I'm trying to make it as easy for catalogers as possible. In the Incipit Search Tool, they will just need to copy and paste the full line in the Macomber ID field instead of selecting a part with ID extension. 
![Select](https://user-images.githubusercontent.com/34317046/84892155-10ea4800-b06b-11ea-858a-ff8434aafa97.jpg)
A field with ID+extension is easily convertable into a field with just an extension if needed for data work.

@rlskoeser @WendyLBelcher Re the names for recensions, Wendy and I discussed it, and for now we think it would be best to refer to them using the source of the incipit ("canonical" for a particular story variation). It will be the most consistent way to label them (some IDs have recensions with and without proper names, some have short and long versions, but a lot of other IDs have differences in plot that cannot be easily labeled). The idea is to begin dividing the records into groups of similar versions during cataloging. Later, with more records in each recension cluster, we might be able to formulate meaningful names for recension IDs.

**Comment by rlskoeser** [comment]
Thanks for explaining — this certainly makes sense in terms of labeling recensions, I can understand that you will need more information to come up with meaningful names.

@elambrinaki I understand better what you are trying to do and how you are approaching it.  just tested, and I can cut and paste two cells of tabular data into two cells in a google sheet. Would this work? A combined field can certainly be split for data analysis, but I can't see how we could validate the contents of a combined field. If we keep them in two fields, it should be easy to make sure that the recension id is valid. (One possible scenario: someone mistakenly copies and pastes an incomplete id and doesn't notice).

**Comment by elambrinaki** [comment]
@rlskoeser This would be wonderful! Thank you for the suggestion.

A question about validation:
For example, ID 7 has two versions. For the records of ID 7 we create, we will find out the recension ID. But for all but one records of ID 7 from Macomber handlist, we wouldn't know the extension as we don't have the incipits of these stories, so they all will remain ID 7.
Is it possible to apply validation on the ID extension field _conditional on the Incipit field being non-empty_? (this would mean we can test the story and find out which recension cluster it belongs)

(ID 7 with incipit and empty ID extension field is a mistake; ID 7 without incipit and without ID Extension is not a mistake)

**Comment by rlskoeser** [comment]
@elambrinaki yes, interesting! I don't know if there's a way to tell the goodtables validation tool to look for that, but if there isn't I don't think it would be hard for us to write as an additional check.

**Comment by elambrinaki** [comment]
Great!

**Comment by rlskoeser** [comment]
@elambrinaki please review the steps I've added to the issue description describing how I'm planning to implement this and make sure it sounds right to you. (Do you agree with the field names, order, help text? Any revisions?)

And please create a new issue to request the conditional validation you're suggesting.

**Comment by elambrinaki** [comment]
@rlskoeser Does this bind us to using manuscript names as recensions ID names? Will we ask you to update validation and help text when we are ready to give meaningful names to recension IDs?

**Comment by rlskoeser** [comment]
@elambrinaki yes, my suggested approach does. Is that too limiting? I suggest you use a new field for recension labels when you have them (and ideally it would be in one place and not repeated, so it might not belong on the story instance sheet — if it's part of the dataset at all).

**Comment by WendyLBelcher** [comment]
@rlskoeser  @elambrinaki Sorry to be slow! Recensions often have to do with manuscripts. That is, the short Qemer stories all come originally from, say, MS X 272, and the long Qemer stories all originally came from MS Y 562. So, keeping recensions tied to manuscripts is a good idea. I do find ID 492 EMML 6085 super clunky, but I can't see a way around it.

**Comment by elambrinaki** [comment]
@rlskoeser @WendyLBelcher Great!
To note, because of the institution abrreviation in a manuscript name, it would be even clunkier: ID 492 EMML **(HMML)** 6085

Rebecca, the proposed steps are clear to me!

**Comment by rlskoeser** [comment]
@WendyLBelcher @elambrinaki do you want this field named "Recension ID" (as we had previously called it when discussing how to implement) or "ID Extension" (as it is currently named in the spreadsheet)?  It doesn't matter to me, just want to be sure we use the field name you prefer.

**Comment by WendyLBelcher** [comment]
@rlskoeser I like "Recension ID" over "ID Extension" but what do you think @elambrinaki ?

**Comment by elambrinaki** [comment]
@WendyLBelcher @rlskoeser Recension ID! Thank you for noticing this, Rebecca!

**Comment by rlskoeser** [comment]
Great! @elambrinaki do you want rename it in Google Sheets so we can work from that (or a copy of it)?

**Comment by kmcelwee** [comment]
The to-do 
> update pemm-data schema for rename from "ID Extension" to "Recension ID"

Is addressed in this pull request: https://github.com/Princeton-CDH/pemm-data/pull/8

**Comment by kmcelwee** [comment]
@elambrinaki I've just deployed to QA. There may be problems with syncing from the QA sheet, which I'm about to work through, but here's the testing checklist I put together:

- [x] Check that results without recension ids do not list "Recension:"
- [x] Compare Recension IDs in results with that in the google sheet and ensure that they are properly displayed together
- [x] Check that the results can be pasted into a google sheet pre-split into two cells

**Comment by elambrinaki** [comment]
@kmcelwee Thank you very much! It works great and is very useful! The only minor thing is that pasting to the sheet requires pasting _values only_, simple Ctrl+V inserts story ID and recension ID into one cell.

**Comment by kmcelwee** [comment]
Hm. That might be a Windows-specific thing. I just double checked on my Mac and it worked fine. If it's easier, I think Ctrl+Shift+V might be shorthand for pasting values only. If that's the only thing, I'm going to merge and deploy to prod. Let me know if that's a problem! 🚀

**Comment by rlskoeser** [comment]
I tested this too — I don't know if behavior is different mac vs windows or different browsers, but I think you may want to use ctrl+shift+v anyway because otherwise you get the formatting from the result page, which you probably don't want.

**Comment by elambrinaki** [comment]
@kmcelwee Yes, please merge and deploy!

**Comment by elambrinaki** [comment]
@rlskoeser Good! We will be using Ctrl+Shift+V.
