### ISSUE TITLE
As a google sheets user, I want validation that prevents me from entering the wrong type of value in a field so that I can avoid preventable errors.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/pemm-scripts#8]
## Notes for testing
- Collection
   - validation for latitude and longitude fields
- Manuscript
   - total folios and total pages should only allow numbers
   - century should be limited to allowed values and format as ##.00
   - date range start and end should require 4-digit year
- Canonical Story
   - Macomber ID should require number with optional -A through -F or -A1/A2
- Story Instance
   - folio validation should require numeric with optional r,v,a,b

---
this encompasses all the regex/type validation stuff from #1

**Comment by elambrinaki** [comment]
### Notes after testing

Story Instance

- folio validation: numeric value (from one to three digits) with optional r,v,a,b (currently only one-digit numbers can be entered)
- "Column start/end" -- validation no more than a single digit (please add this validation)
- "Line start/end" -- no more than two digits (please add this validation)

Story instance sheet

- Number of paintings - no more than one digit (please add this validation)

Everything not mentioned works well.

**Comment by WendyLBelcher** [comment]
Story instance sheet
Number of paintings - no more than one digit

**Comment by rlskoeser** [comment]
As decided in the meeting last week, we will not add any new validation or constraints that go beyond the _type_ of value (numeric, string, etc).

Only change to be tested is that the folio validation allows more than one digit (previously version only allowed one digit).

**Comment by WendyLBelcher** [comment]
The validation for the Folio column in the Story Instance Sheet works, but the column needs to be split into two columns: Folio Start and Folio End. They should both have the same validation they currently have. And they should be inserted the in this column order: "Folio Start, Column Start, Line Start; Folio End, Column End, Line End."

**Comment by rlskoeser** [comment]
Have generated a new test spreadsheet for review. Please confirm that the Folio/Column/Line fields are present and ordered as requested, and that folio validation is working properly on both Folio Start and Folio End.

**Comment by WendyLBelcher** [comment]
Yes, thank you. it looks good!
